title: Project

columns:
  left: 
    width: 2/3
    sections:
      content: 
        type: fields
        fields:
          student:
            type: text  
            width: 1/2
          class:
            type: text  
            width: 1/4
          year:
            type: text
            width: 1/4 
          link url:
            type: text              
            width: 1/2
          link text:
            type: text
            width: 1/2     
          tags:
            label: Tags
            type: tags
            width: 1
          excerpt:
            type: textarea
            size: large
  right: 
    width: 1/3
    sections:
      cover:
        headline: Cover
        template: cover
        type: files      
      gallery: 
        type: files
        layout: cards
        image: 
          cover: true            